package com.model;

/**
 * TYuding generated by MyEclipse Persistence Tools
 */

public class TYuding implements java.io.Serializable
{

	// Fields

	private Integer id;

	private Integer userId;

	private Integer qchId;

	private Integer tianshu;

	private String yudingzheTel;
	
	private String shijian;

	private String del;
	private String sjdlist;
	private TUser user;
	private TQch qch;


	private String ydrq;
	private String paystatus;
	private String hystatus;
	private String hycode;
	private String jingdu;

	public String getJingdu() {
		return jingdu;
	}

	public void setJingdu(String jingdu) {
		this.jingdu = jingdu;
	}

	public String getPaystatus() {
		return paystatus;
	}

	public void setPaystatus(String paystatus) {
		this.paystatus = paystatus;
	}

	public String getHystatus() {
		return hystatus;
	}

	public void setHystatus(String hystatus) {
		this.hystatus = hystatus;
	}

	public String getHycode() {
		return hycode;
	}

	public void setHycode(String hycode) {
		this.hycode = hycode;
	}

	public String getYdrq() {
		return ydrq;
	}

	public void setYdrq(String ydrq) {
		this.ydrq = ydrq;
	}

	public String getSjdlist() {
		return sjdlist;
	}

	public void setSjdlist(String sjdlist) {
		this.sjdlist = sjdlist;
	}
// Constructors

	/** default constructor */
	public TYuding()
	{
	}

	/** full constructor */
	public TYuding(Integer userId, Integer qchId, Integer tianshu,
			String yudingzheTel, String del)
	{
		this.userId = userId;
		this.qchId = qchId;
		this.tianshu = tianshu;
		this.yudingzheTel = yudingzheTel;
		this.del = del;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}
    
	public TQch getQch()
	{
		return qch;
	}

	public void setQch(TQch qch)
	{
		this.qch = qch;
	}

	public TUser getUser()
	{
		return user;
	}

	public void setUser(TUser user)
	{
		this.user = user;
	}

	public String getShijian()
	{
		return shijian;
	}

	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getUserId()
	{
		return this.userId;
	}

	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}

	public Integer getQchId()
	{
		return this.qchId;
	}

	public void setQchId(Integer qchId)
	{
		this.qchId = qchId;
	}

	public Integer getTianshu()
	{
		return this.tianshu;
	}

	public void setTianshu(Integer tianshu)
	{
		this.tianshu = tianshu;
	}

	public String getYudingzheTel()
	{
		return this.yudingzheTel;
	}

	public void setYudingzheTel(String yudingzheTel)
	{
		this.yudingzheTel = yudingzheTel;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}